"""
Project Euler #2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

"""

threshold = 4000000

def fib_gen():
    prev = 1
    cur = 1
    total_sum = 0


    while total_sum < threshold:
        next = cur + prev
        prev = cur 
        cur = next

        if next % 2 == 0:
            total_sum += next

    print(total_sum)


fib_gen()